---
name: idr0061-wolf-spindlepositioning/screenA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: no
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split: ","
  # Should this column be included in the clients (yes/no)
  includeclient: yes
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: yes
  # Should empty values be omitted from the client display
  omitempty: yes

columns:

  - name: Sense Sequence
    clientname: Sense Sequence
    include: yes

  - name: Control Type
    clientname: Control Type
    include: yes

  - name: Control Comments
    clientname: Control Comments
    include: yes

  - name: Reagent Identifier
    clientname: Reagent Identifier
    include: yes

  - name: Quality Control
    clientname: Quality Control
    include: yes

  - name: Comments
    clientname: Comments
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
        - name: Characteristics [Cell Line]
          clientname: Cell Line
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Gene Symbol
          include: yes
        - name: Gene Identifier
          include: yes
        - name: Gene Identifier
          clientname: Gene Identifier URL
          clientvalue: https://www.ncbi.nlm.nih.gov/gene/{{ value|urlencode }}
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene/supplementary
      columns:
        - name: Gene Annotation Comments
          clientname: Gene Annotation
          include: yes

advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
